//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Core.Error {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CC.Core.Error.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied Divice.
        /// </summary>
        public static string DeniedDivice {
            get {
                return ResourceManager.GetString("DeniedDivice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist Entity. The serial number is the same.
        /// </summary>
        public static string ExistEntity {
            get {
                return ResourceManager.GetString("ExistEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway with more 10 Device.
        /// </summary>
        public static string GatewayOcupation {
            get {
                return ResourceManager.GetString("GatewayOcupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP does not valid.
        /// </summary>
        public static string IsNotValidIP {
            get {
                return ResourceManager.GetString("IsNotValidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device can be added. Gateway does not exist.
        /// </summary>
        public static string NotExistGateway {
            get {
                return ResourceManager.GetString("NotExistGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device can be added. Status does not exist.
        /// </summary>
        public static string NotExistStatus {
            get {
                return ResourceManager.GetString("NotExistStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity does not exist.
        /// </summary>
        public static string NotExitEntity {
            get {
                return ResourceManager.GetString("NotExitEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity null.
        /// </summary>
        public static string ObjectNull {
            get {
                return ResourceManager.GetString("ObjectNull", resourceCulture);
            }
        }
    }
}
